import { MARKET_NAME } from './env';

export const MOCK_TOKEN_PREFIX = `MockToken-`;
export const ADDRESSES_PROVIDER_ID = `AddressesProvider`;
export const ROLE_MANAGER_ID = `RoleManager`;
export const ORACLE_PRICE_FEED_ID = `OraclePriceFeed`;
export const MOCK_PRICE_FEED_PREFIX = `MockPriceFeed-`;
export const INDEX_PRICE_FEED_ID = `IndexPriceFeed`;
export const PAIR_INFO_ID = `Pool`;
export const POOL_TOKEN_FACTORY = `PoolTokenFactory`;
export const PAIR_LIQUIDITY_ID = `PoolLiquidity`;
export const TRADING_VAULT_ID = `PositionManager`;
export const ROUTER_ID = `Router`;
export const EXECUTOR_ID = `Executor`;
export const ORDER_MANAGER_ID = `OrderManager`;
export const POSITION_MANAGER_ID = `PositionManager`;
export const TEST_CALLBACK_ID = `TestCallBack`;
export const MYX_ID = `MYX`;
export const RAMYX_ID = `RaMYX`;
export const STMYX_ID = `StMYX`;
export const VESTER_ID = `Vester`;
export const STAKING_POOL_ID = `StakingPool`;
export const LP_STAKING_POOL_ID = `LPStakingPool`;
export const CONVERTOR_ID = `Convertor`;
export const REWARD_DISTRIBUTOR_ID = `RewardDistributor`;
