hh run scripts/price/setPrices.js --network $1
hh run scripts/pair/addLiquidity.js --network $1
hh run scripts/trading/increaseMarketLong.js --network $1
hh run scripts/trading/increaseLimitShort.js --network $1
hh run scripts/trading/decreaseMarketLong.js --network $1
hh run scripts/trading/decreaseLimitShort.js --network $1
hh run scripts/trading/createAndExecuteTp.js --network $1
hh run scripts/trading/createAndExecuteSl.js --network $1
hh run scripts/trading/testLpStableReserve.js --network $1
hh run scripts/trading/liquidate.js --network $1
hh run scripts/trading/adl.js --network $1
